[project]
name = "creatorbox"
version="1.0.25"
description="ðŸš€ðŸŽ¬ Flexible, efficient, and scalable toolbox for editing and dubbing, unleashing creative potential"
readme = "README.md"
requires-python = ">=3.10,<3.14"
dependencies = [
    "apscheduler==3.11.0",
    "asyncio==4.0.0",
    "azure-cognitiveservices-speech==1.45.0",
    "babel==2.17.0",
    "click==8.3.0",
    "dashscope==1.23.5",
    "edge-tts==7.2.1",
    "elevenlabs==2.14.0",
    "fast-langdetect==0.3.2",
    "fastapi==0.116.1",
    "faster-whisper==1.2.0",
    "ffmpeg-python==0.2.0",
    "firebase-admin==6.9.0",
    "funasr==1.2.7",
    "func-timeout==4.3.5",
    "gcloud==0.18.3",
    "gputil==1.4.0",
    "gradio==5.34.0",
    "gradio-bottombar==0.0.2",
    "gradio-videoslider==0.0.2",
    "langchain==0.3.27",
    "langchain-community==0.3.21",
    "langchain-google-genai==2.1.9",
    "langchain-openai==0.3.31",
    "language-tags==1.2.0",
    "librosa==0.10.2",
    "loguru==0.7.3",
    "moviepy==1.0.3",
    "nltk==3.9.1",
    "numpy==1.26.4",
    "oauth2client==4.1.3",
    "opencv-python==4.11.0.86",
    "psutil==7.0.0",
    "pyannote-audio==3.3.2",
    "pyarmor==9.1.2",
    "pydub==0.25.1",
    "pyjianyingdraft==0.2.5",
    "pyngrok==7.3.0",
    "python-engineio==4.12.2",
    "python-jwt==4.1.0",
    "python-multipart==0.0.20",
    "python-socketio==5.13.0",
    "requests-cache==1.2.1",
    "srt==3.5.3",
    "tenacity==9.1.2",
    "tinydb==4.8.2",
    "torch==2.6.0",
    "torchaudio==2.6.0",
    "torchvision==0.21.0",
    "transformers==4.51.3",
    "uvicorn==0.35.0",
    "yt-dlp==2025.10.22",
]

[dependency-groups]
dev = [
    "autoflake>=2.3.1",
    "babel>=2.17.0",
    "black>=25.9.0",
    "pip>=25.3",
    "polib>=1.2.0",
    "ruff>=0.14.2",
    "vulture>=2.14",
]
uvr = [
    "audio-separator==0.30.2",
]
vsd = [
    "scenedetect==0.6.7",
]
vse = [
    "rapidocr==3.3.1",
]

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true
